### ISSUE TITLE
Required PHP Version

### ISSUE THREAD

**Issue by obstschale** [dmhendricks/wordpress-base-plugin#4]
Hey man,

just a quick hint. In your `composer.json` you require `"php": ">=5.3.29"`. But in multiple files you're using PHP's short array syntax `[ 'value' ]`, which is available from PHP 5.4+.

**Comment by dmhendricks** [comment]
Thank you for the reminder. I fixed most of them, but eventually decided just to bump the minimum PHP to 5.4 (I did not commit it yet) because many dependencies use the short form. I'm still going to fix my own because this plugin could still be used with 5.3 if you remove the PostTypes (and any other dependencies) that use brackets.

I will leave this issue open until I have time to commit the changes.

**Comment by dmhendricks** [comment]
Ok, I just pushed this. Thanks again!
